
interface TextureInfo {
    name: string;
    type: 'wall' | 'floor' | 'roof';
    data: string;
}

// Simple Base64 encoded 64x64 textures to replace file paths
const textures = {
    plasterWhite: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABTSURBVHhe7c4xEQAgDMCwgH/fnoAEC2fsc/kC4G3g/QEAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAgSQAAwB+7wAB2s1pAAAAAElFTkSuQmCC',
    woodLight: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACLSURBVHhe7dixCQAgEMNAf/d/lS8oCw1L2WwHnKd4nQUAgM0B3gABQEAChIAECFEBAlRAgB8QEAChIAECVECAExAQgFAIBCBi/wV8gYAECEEBAlRAgBsgIAFCEAhAxP47cAECEpCAFBQggAUIgIAECFEBAlRAgAcISCC/93MHDwAhSEACUlCAABSggAAECJm4AAdc5rM5AAAAAElFTkSuQmCC',
    stoneGrey: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACRSURBVHhe7dmxCQAgEANBvf+d6wI72vSwEV/uMh3g55bT/ACAeQMSkIAUFECAAhQggAAISCCw/i2cDyAgAUGg/r3gAQQkQAgCEKg/C15AQAKCABD9f4YvICABQUACUlCAAhQggAAISCCw/i2cDyAgAUGg/r3gAQQkQAgCEKg/C15AQAKCABD9v+EFCEhAAgqg8wQy41/dYQAAAABJRU5ErkJggg==',
    woodDark: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACLSURBVHhe7dixCQAgEMNAb/d/lS+oCw1L2WwHnKd4nQUAgM0B3gABQEAChIAECFEBAlRAgB8QEAChIAECVECAExAQgFAIBCBi/wV8gYAECEEBAlRAgBsgIAFCEAhAxP47cAECEpCAFBQggAUIgIAECFEBAlRAgAcISCC/93MHDwAhSEACUlCAABSggAAECJm4AAVo4bM5AAAAAElFTkSuQmCC',
    stoneTiles: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABmSURBVHhe7c1hCQAgDACw/f+nF9hBhbJk2s5zAgAAYGfg4QcQkIAUFECAAhQggAAEJAAY5ecVEJCAoAAACFCAAAIQkADg/Cg9AQEJCAoAgQIUIICABASA/I7TCwhIQAp6AFg/AfVf7w2/AAAAAElFTkSuQmCC',
    carpetRed: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABASURBVHhe7cExAQAAAMKg9U9tCF+gYCKAmwMAAAABAACAAAEAAICAACAAAAQIAAAABAgAAAECAIBAAAACBAAAAP4B1aQAAEeuIQwAAAAASUVORK5CYII=',
    roof: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB6SURBVHhe7dGxDYAwDAXQ///pD0o2gQhW2o52+DPPew8A8H4AQQFCEIBAgAIUISABhQAECFIQAQhQhIAEUogAAYIoQwACEKEgASlEAAFBFCMAASJCQQJSiAAAgihGAAIQISEBCSgEAQhQhIAEFCIAAQhRhAAECFIQAQhQ5AcsVgFU3fN3/gAAAABJRU5ErkJggg==',
    plasterWhiteWindow: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADISURBVHhe7dJBCoAwDATB0v+8/6F6SIUjS2o4Bw/3sJgDAFhfYmQnSUiAUpCAhAQtQEhAQpCApCAhAQlQAhKQgKQgIQEJUAsSkICkICEBCVAaEpCApCAhAQlQCxKQgKQgIQEJUBoSkICkICEBCVALEpCApCAhAQlQGhKQgKQgIQEJUAsSkICkICEBCVAaEpCApCAhAQlQGgQkQClIQAKSghYgJCAhCUhBSkJCAhKgBCQgAUlBQgISoBYkIAFJQULS+gB/4v0D9o+B3Qd2PzC+d/IBAwB3GQFjIIP5QAAAAABJRU5ErkJggg==',
    stoneGreyWindow: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADeSURBVHhe7dLBCYAwDAPAsv/e/6DqYIULSU3n4OEexuIAAJYnMzKbJCQgAUpCAhLQFCABKQgJSEACkpCQgAQoAcnYgAQkBQkJSIASEJCABGQNCQlIgBKQgAQkJQkJSIASEJCABGQNCQlIgBKQgAQkJQkJSIASEJCABGQNCQlIgBKQgAQkJQlIQBKQhAQkaAkQEJCABKQgCUpCQgIQoAQkIAFJQUL2H8C33d4G+8fA7gO7HxhfO/kAAQDcZQTf4YP6wAAAAABJRU5ErkJggg==',
    woodDarkWindow: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADTSURBVHhe7dLBCYAwDAPAsn+8/6HqYYULSU3n4OEexuIAAJYnMzKbJCQgAUpCAhLQFCABKQgJSEACkpCQgAQoAcnYgAQkBQkJSIASEJCABGQNCQlIgBKQgAQkJQkJSIASEJCABGQNCQlIgBKQgAQkJQkJSIASEJCABGQNCQlIgBKQgAQkJQlIQBKQhAQkaAkQEJCABKQgCUpCQgIQoAQkIAFJQUL2H8C33d4G+8fA7gO7HxhfO/kAAQDcZQRQ4IP7wAAAAABJRU5ErkJggg==',
};

export const TEXTURE_LIBRARY: Record<string, TextureInfo> = {
    // Default Fallbacks
    'wall_plaster_white': { name: 'White Plaster', type: 'wall', data: textures.plasterWhite },
    'floor_wood_light': { name: 'Light Wood Planks', type: 'floor', data: textures.woodLight },

    // Walls
    'wall_plaster_whiteWithWindow': { name: 'White Plaster (Window)', type: 'wall', data: textures.plasterWhiteWindow },
    'wall_stone_grey': { name: 'Grey Stone', type: 'wall', data: textures.stoneGrey },
    'wall_stone_greyWithWindow': { name: 'Grey Stone (Window)', type: 'wall', data: textures.stoneGreyWindow },
    'wall_wood_dark': { name: 'Dark Wood Panels', type: 'wall', data: textures.woodDark },
    'wall_wood_darkWithWindow': { name: 'Dark Wood Panels (Window)', type: 'wall', data: textures.woodDarkWindow },

    // Floors
    'floor_stone_tiles': { name: 'Stone Tiles', type: 'floor', data: textures.stoneTiles },
    'floor_carpet_red': { name: 'Ornate Red Carpet', type: 'floor', data: textures.carpetRed },

    // Roofs
    'flatRoof': { name: 'Flat Roof', type: 'roof', data: textures.roof },
};
